# Regenie - any ancestry pipeline

Goal is to make a pipeline where you just provide ancestry and it preps everything until running regenie directly!

Regenie seems to be best for maximizing sample size is relatively small cohorts. So let's test:

* AAC
* CAS
* MDE

Now for the true multi-ancestry GWAS, IMO we should do MAF > 0.005 (calculated for controls only).

This is just a test!

---
What is REGENIE?

REGENIE is an analysis program that can be used for Biobank-level GWAS/burden analysis. Why use Regenie? It can account for relatedness to increase sample size, use firth-correction for lopsided case-control ratios, reduce phenotype variance (by accounting for polygenic effect outside of the tested SNP), and you can run multiple phenotypes at the same time efficiently. SAIGE can also account for relatedness but 1. is much slower 2. effect size may be inflated by using SPA correction.

Also unlike SAIGE, the error messages actually make sense.

1. Define phenotypes and participants
2. Prepare regenie step 1 file
3. Run Regenie step 1
4. Run Regenie step 2

Note that step 1 and 2 DO NOT share the same input. Step 1 is used to generate a whole-genome model to account for relatedness, so you will just use unimputed genotyped data (with proper QC). Step 2 can be any data e.g. WGS, imputed, etc. Step 1 and 2 do not have to share file types (plink 1 bed vs plink2 pgen) or even genome build (hg19 vs hg38)!

Some links to help you:

- Regenie documentation: https://rgcgithub.github.io/regenie/
- Regenie manuscript: https://www.nature.com/articles/s41588-021-00870-7
- Github: https://github.com/rgcgithub/regenie/

In [ ]:
# Edit only this section before running the notebook from the top.
from pathlib import Path
import os

ANC = "FIN"
RELEASE = 12 

# Folder in which this notebook should create data/ and output/.
PROJECT_DIR = Path.cwd()

# Root of the GP2 release mounted in verily
GP2_RELEASE_DIR = Path("/home/jupyter/workspace/gp2_tier2_eu_release12")

# Existing hg38 blacklist BED file. This file is read directly, never copied. Jeff gave us this file
BLACKLIST_BED = Path("/home/jupyter/workspace/ws_files/MAMA_2/FirstTryApril26/data/hg38-blacklist.v2.bed")

# Use command names when plink2/regenie are on PATH, or enter full paths.
PLINK2 = "plink2"
REGENIE = "regenie"
THREADS = 8
CHROMOSOMES = range(1, 23)
STEP2_CHROMOSOMES = CHROMOSOMES

# standard settings so the paths will work, not really need to change anything bellow here
PROJECT_DIR = PROJECT_DIR.expanduser().resolve()
GP2_RELEASE_DIR = GP2_RELEASE_DIR.expanduser().resolve()
BLACKLIST_BED = BLACKLIST_BED.expanduser().resolve()
RELEASE_TAG = f"R{RELEASE}"
RELEASE_SUFFIX = f"release{RELEASE}_vwb"
R12_DIR = str(GP2_RELEASE_DIR)  
os.chdir(PROJECT_DIR)
for directory in (PROJECT_DIR / "data", PROJECT_DIR / "output"):
    directory.mkdir(parents=True, exist_ok=True)

if not GP2_RELEASE_DIR.is_dir():
    raise FileNotFoundError(f"GP2_RELEASE_DIR does not exist: {GP2_RELEASE_DIR}")
if not BLACKLIST_BED.is_file():
    raise FileNotFoundError(
        f"BLACKLIST_BED does not exist: {BLACKLIST_BED}. Update it in the config cell."
    )

print(f"Ancestry: {ANC} | Release: {RELEASE} | Threads: {THREADS}")
print(f"Project directory: {PROJECT_DIR}")
print(f"GP2 release directory: {GP2_RELEASE_DIR}")
print(f"Blacklist BED: {BLACKLIST_BED}")


import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
from scipy.special import log_ndtr
import sys
import networkx as nx
from typing import Set, List, Tuple, Dict

Ancestry: FIN | Release: 12 | Threads: 8
Project directory: /home/jupyter/workspace/ws_files/MAMA_2/jf_release12/test
GP2 release directory: /home/jupyter/workspace/gp2_tier2_eu_release12
Blacklist BED: /home/jupyter/workspace/ws_files/MAMA_2/FirstTryApril26/data/hg38-blacklist.v2.bed

In [4]:
#os.chdir('')

### Define ancestry

In [5]:
# ANC is set in the collaborator configuration cell above.
print(ANC)

FIN

### Define Release path

In [6]:
# GP2_RELEASE_DIR / R12_DIR are set in the collaborator configuration cell.
print(GP2_RELEASE_DIR)

/home/jupyter/workspace/gp2_tier2_eu_release12

In [7]:
# !mkdir -p ./data/symlink_R12_{ANC}
# !pwd
!pwd
!mkdir -p ./data/symlink_R12_{ANC}

/home/jupyter/workspace/ws_files/MAMA_2/jf_release12/test

In [8]:
print(ANC)

FIN

# 1. Create symlink because psam needs FID

In [9]:
for CHRNUM in CHROMOSOMES:
    CMD = f'{PLINK2} --pfile {R12_DIR}/imputed_genotypes/{ANC}/chr{CHRNUM}_{ANC}_release12_vwb \
    --write-snplist \
    --make-just-psam cols=+fid --out data/symlink_R12_{ANC}/chr{CHRNUM}_{ANC}_release12_vwb'
    !$CMD

PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr1_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr1_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:19 2026
52195 MiB RAM detected, ~18434 available; reserving 18370 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.psam.
1079262 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr1_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr1_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:21 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr2_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr2_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:22 2026
52195 MiB RAM detected, ~18409 available; reserving 18345 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.psam.
1161330 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr2_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr2_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:24 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr3_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr3_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:25 2026
52195 MiB RAM detected, ~18336 available; reserving 18272 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.psam.
973595 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr3_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr3_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:27 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr4_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr4_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:28 2026
52195 MiB RAM detected, ~18335 available; reserving 18271 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.psam.
987128 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr4_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr4_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:30 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr5_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr5_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:31 2026
52195 MiB RAM detected, ~18336 available; reserving 18272 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.psam.
893931 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr5_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr5_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:32 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr6_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr6_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:34 2026
52195 MiB RAM detected, ~18329 available; reserving 18265 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.psam.
891266 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr6_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr6_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:35 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr7_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr7_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:36 2026
52195 MiB RAM detected, ~18332 available; reserving 18268 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.psam.
798427 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr7_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr7_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:38 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr8_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr8_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:39 2026
52195 MiB RAM detected, ~18342 available; reserving 18278 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.psam.
754331 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr8_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr8_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:40 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr9_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr9_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:42 2026
52195 MiB RAM detected, ~18340 available; reserving 18276 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.psam.
590093 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr9_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr9_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:43 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr10_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr10_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:44 2026
52195 MiB RAM detected, ~18343 available; reserving 18279 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb.psam.
692560 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr10_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr10_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:46 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr11_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr11_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:47 2026
52195 MiB RAM detected, ~18324 available; reserving 18260 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.psam.
671250 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr11_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr11_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:48 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr12_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr12_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:50 2026
52195 MiB RAM detected, ~18334 available; reserving 18270 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.psam.
657130 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr12_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr12_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:50 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr13_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr13_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:52 2026
52195 MiB RAM detected, ~18337 available; reserving 18273 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.psam.
504455 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr13_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr13_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:53 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr14_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr14_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:54 2026
52195 MiB RAM detected, ~18326 available; reserving 18262 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.psam.
444435 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr14_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr14_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:55 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr15_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr15_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:56 2026
52195 MiB RAM detected, ~18331 available; reserving 18267 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.psam.
391883 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr15_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr15_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:18:57 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr16_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr16_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:18:59 2026
52195 MiB RAM detected, ~18351 available; reserving 18287 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.psam.
425046 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr16_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr16_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:19:00 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr17_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr17_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:19:01 2026
52195 MiB RAM detected, ~18319 available; reserving 18255 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.psam.
373594 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr17_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr17_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:19:02 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr18_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr18_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:19:03 2026
52195 MiB RAM detected, ~18324 available; reserving 18260 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb.psam.
393015 variants loaded from

In [13]:
# CMD1 = f'mkdir -p data/symlink_R12_{ANC}; \
# ln -s $(realpath {R12_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release11_vwb.'
# CMD2 = '{pvar,pgen}) '
# CMD3 = f'data/symlink_R12_{ANC}/'
# SYMLINK_CMD = CMD1+CMD2+CMD3
# !bash ls "$SYMLINK_CMD"

SYMLINK_CMD = (
    f"mkdir -p data/symlink_R12_{ANC}; "
    f"ln -s $(realpath {R12_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release12_vwb.{{pvar,pgen}}) "
    f"data/symlink_R12_{ANC}/"
)

print(SYMLINK_CMD)
!bash -lc "$SYMLINK_CMD"

mkdir -p data/symlink_R12_FIN; ln -s $(realpath /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr*_FIN_release12_vwb.{pvar,pgen}) data/symlink_R12_FIN/
ln: failed to create symbolic link './chr10_FIN_release12_vwb.pvar': File exists
bash: line 2: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.pvar: Permission denied
bash: line 3: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.pvar: Permission denied
bash: line 4: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.pvar: Permission denied
bash: line 5: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.pvar: Permission denied
bash: line 6: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.pvar: Permission denied
bash: line 7: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.pvar: Permission denied
bash: line 8: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.pvar: Permission denied
bash: line 9: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb.pvar: Permission denied
bash: line 10: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr19_FIN_release12_vwb.pvar: Permission denied
bash: line 11: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.pvar: Permission denied
bash: line 12: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr20_FIN_release12_vwb.pvar: Permission denied
bash: line 13: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr21_FIN_release12_vwb.pvar: Permission denied
bash: line 14: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr22_FIN_release12_vwb.pvar: Permission denied
bash: line 15: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.pvar: Permission denied
bash: line 16: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.pvar: Permission denied
bash: line 17: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.pvar: Permission denied
bash: line 18: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.pvar: Permission denied
bash: line 19: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.pvar: Permission denied
bash: line 20: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.pvar: Permission denied
bash: line 21: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.pvar: Permission denied
bash: line 22: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.pvar: Permission denied
bash: line 23: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_female_FIN_release12_vwb.pvar: Permission denied
bash: line 24: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_male_non_PAR_FIN_release12_vwb.pvar: Permission denied
bash: line 25: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_male_PAR_FIN_release12_vwb.pvar: Permission denied
bash: line 26: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb.pgen: Permission denied
bash: line 27: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.pgen: Permission denied
bash: line 28: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.pgen: Permission denied
bash: line 29: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.pgen: Permission denied
bash: line 30: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.pgen: Permission denied
bash: line 31: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.pgen: Permission denied
bash: line 32: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.pgen: Permission denied
bash: line 33: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.pgen: Permission denied
bash: line 34: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb.pgen: Permission denied
bash: line 35: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr19_FIN_release12_vwb.pgen: Permission denied
bash: line 36: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.pgen: Permission denied
bash: line 37: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr20_FIN_release12_vwb.pgen: Permission denied
bash: line 38: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr21_FIN_release12_vwb.pgen: Permission denied
bash: line 39: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr22_FIN_release12_vwb.pgen: Permission denied
bash: line 40: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.pgen: Permission denied
bash: line 41: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.pgen: Permission denied
bash: line 42: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.pgen: Permission denied
bash: line 43: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.pgen: Permission denied
bash: line 44: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.pgen: Permission denied
bash: line 45: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.pgen: Permission denied
bash: line 46: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.pgen: Permission denied
bash: line 47: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.pgen: Permission denied
bash: line 48: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_female_FIN_release12_vwb.pgen: Permission denied
bash: line 49: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_male_non_PAR_FIN_release12_vwb.pgen: Permission denied
bash: line 50: /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chrX_male_PAR_FIN_release12_vwb.pgen: Permission denied

In [14]:
!ls -lh data/symlink_R12_{ANC}

total 245M
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr10_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr10_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  13M Sep  3 14:18 chr10_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr11_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr11_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  13M Sep  3 14:18 chr11_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr12_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr12_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  13M Sep  3 14:18 chr12_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr13_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr13_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 9.3M Sep  3 14:18 chr13_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr14_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr14_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 8.2M Sep  3 14:18 chr14_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr15_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr15_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 7.2M Sep  3 14:18 chr15_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr16_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr16_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 7.7M Sep  3 14:18 chr16_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr17_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr17_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 6.8M Sep  3 14:19 chr17_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr18_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr18_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 7.2M Sep  3 14:19 chr18_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr19_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr19_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 5.5M Sep  3 14:19 chr19_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr1_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr1_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  20M Sep  3 14:18 chr1_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr20_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr20_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 5.7M Sep  3 14:19 chr20_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr21_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr21_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 3.4M Sep  3 14:19 chr21_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:19 chr22_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:19 chr22_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users 3.4M Sep  3 14:19 chr22_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr2_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr2_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  21M Sep  3 14:18 chr2_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr3_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr3_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  18M Sep  3 14:18 chr3_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr4_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr4_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  18M Sep  3 14:18 chr4_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr5_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr5_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  16M Sep  3 14:18 chr5_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr6_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr6_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  16M Sep  3 14:18 chr6_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr7_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr7_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  15M Sep  3 14:18 chr7_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr8_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr8_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  14M Sep  3 14:18 chr8_FIN_release12_vwb.snplist
-rw-rw-rw-. 1 jupyter users 1.1K Sep  3 14:18 chr9_FIN_release12_vwb.log
-rw-rw-rw-. 1 jupyter users 6.0K Sep  3 14:18 chr9_FIN_release12_vwb.psam
-rw-rw-rw-. 1 jupyter users  11M Sep  3 14:18 chr9_FIN_release12_vwb.snplist

In [15]:
print(ANC)

FIN

In [16]:
# CMD1 = f'mkdir -p ./data/symlink_R11_{ANC}; \
# ln -s $(realpath {R11_DIR}/raw_genotypes/{ANC}/{ANC}'
# CMD2 = '_release11_vwb.{pvar,pgen}) '
# CMD3 = f'data/symlink_R11_{ANC}/'
# SYMLINK_CMD = CMD1+CMD2+CMD3
# !bash -lc $SYMLINK_CMD

SYMLINK_CMD = (
    f"mkdir -p data/symlink_R12_{ANC}; "
    f"ln -s $(realpath {R12_DIR}/raw_genotypes/{ANC}/{ANC}_release12_vwb.{{pvar,pgen}}) "
    f"data/symlink_R12_{ANC}/"
)

print(SYMLINK_CMD)
!bash -lc "$SYMLINK_CMD"

mkdir -p data/symlink_R12_FIN; ln -s $(realpath /home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.{pvar,pgen}) data/symlink_R12_FIN/
bash: line 2: /home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.pgen: Permission denied

In [17]:
print(ANC)

FIN

In [18]:
CMD = f'{PLINK2} --pfile {R12_DIR}/raw_genotypes/{ANC}/{ANC}_release12_vwb \
--make-just-psam cols=+fid --out data/symlink_R12_{ANC}/{ANC}_release12_vwb'
!$CMD

PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb

Start time: Thu Sep  3 14:23:54 2026
52195 MiB RAM detected, ~18424 available; reserving 18360 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.psam.
1 binary phenotype loaded (126 cases, 20 controls).
Writing data/symlink_R12_FIN/FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:23:54 2026

# 2. Consult Regenie Manual

In [19]:
print(ANC)

FIN

In [20]:
!{REGENIE} --help

              |=============================|
              |      REGENIE v4.1.2.gz      |
              |=============================|

Copyright (c) 2020-2024 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.


Usage:
  regenie [OPTION...]

  -h, --help      print list of available options
      --helpFull  print list of all available options

 Main options:
      --step INT                specify if fitting null model (=1) or
                                association testing (=2)
      --bed PREFIX              prefix to PLINK .bed/.bim/.fam files
      --pgen PREFIX             prefix to PLINK2 .pgen/.pvar/.psam files
      --bgen FILE               BGEN file
      --sample FILE             sample file corresponding to BGEN file
      --bgi FILE                index bgi file corresponding to BGEN file
      --ref-first               use the first allele as the reference for
                                BGEN or PLINK bed/bim/fam input format
                                [default assumes reference is last]
      --keep FILE               comma-separated list of files listing
                                samples to retain in the analysis (no
                                header; starts with FID IID)
      --remove FILE             comma-separated list of files listing
                                samples to remove from the analysis (no
                                header; starts with FID IID)
      --extract FILE            comma-separated list of files with IDs of
                                variants to retain in the analysis
      --exclude FILE            comma-separated list of files with IDs of
                                variants to remove from the analysis
  -p, --phenoFile FILE          phenotype file (header required starting
                                with FID IID)
      --phenoCol STRING         phenotype name in header (use for each
                                phenotype to keep; can use parameter
                                expansion {i:j})
      --phenoColList STRING,..,STRING
                                comma separated list of phenotype names to
                                keep (can use parameter expansion {i:j})
      --eventColList STRING,..,STRING
                                comma separated list of event status names
                                to keep (can use parameter expansion {i:j})
  -c, --covarFile FILE          covariate file (header required starting
                                with FID IID)
      --covarCol STRING         covariate name in header (use for each
                                covariate to keep; can use parameter
                                expansion {i:j})
      --covarColList STRING,..,STRING
                                comma separated list of covariate names to
                                keep (can use parameter expansion {i:j})
      --catCovarList STRING,..,STRING
                                comma separated list of categorical
                                covariates
  -o, --out PREFIX              prefix for output files
      --qt                      analyze phenotypes as quantitative
      --bt                      analyze phenotypes as binary
      --t2e                     analyze phenotypes as time to event
  -1, --cc12                    use control=1,case=2,missing=NA encoding
                                for binary traits
  -b, --bsize INT               size of genotype blocks
      --cv INT(=5)              number of cross validation (CV) folds
      --loocv                   use leave-one out cross validation (LOOCV)
      --l0 INT(=5)              number of ridge parameters to use when
                                fitting models within blocks [evenly spaced
                                in (0,1)]
      --l1 INT(=5)              number of ridge parameters to use when
                                fitting model across blocks [evenly spaced
                                in (0,1)]
      --lowmem                  reduce memory usage by writing level 0
                                predictions to temporary files
      --lowmem-prefix PREFIX    prefix where to write the temporary files
                                in step 1 (default is to use prefix from
                                --out)
      --split-l0 PREFIX,N       split level 0 across N jobs and set prefix
                                of output files
      --run-l0 FILE,K           run level 0 for job K in {1..N} using
                                master file created from '--split-l0'
      --run-l1 FILE             run level 1 using master file from
                                '--split-l0'
      --l1-phenoList STRING,...,STRING
                                run level 1 for a subset of the phenotypes
                                (specified as comma-separated list)
      --keep-l0                 avoid deleting the level 0 predictions
                                written on disk after fitting the level 1
                                models
      --strict                  remove all samples with missingness at any
                                of the traits
      --print-prs               also output polygenic predictions without
                                using LOCO (=whole genome PRS)
      --gz                      compress output files (gzip format)
      --apply-rint              apply Rank-Inverse Normal Transformation to
                                quantitative traits
      --apply-rerint            apply Rank-Inverse Normal Transformation to
                                residualized quantitative traits in step 2
      --apply-rerint-cov        apply Rank-Inverse Normal Transformation to
                                residualized quantitative traits and
                                project covariates out in step 2
      --threads INT             number of threads
      --pred FILE               file containing the list of predictions
                                files from step 1
      --ignore-pred             skip reading predictions from step 1
                                (equivalent to linear/logistic regression
                                with only covariates)
      --use-prs                 when using whole genome PRS step 1 output
                                in '--pred'
      --write-samples           write IDs of samples included for each
                                trait (only in step 2)
      --minMAC FLOAT(=5)        minimum minor allele count (MAC) for tested
                                variants
      --minINFO DOUBLE(=0)      minimum imputation info score (Impute/Mach
                                R^2) for tested variants
      --no-split                combine asssociation results into a single
                                for all traits
      --firth                   use Firth correction for p-values less than
                                threshold
      --approx                  use approximation to Firth correction for
                                computational speedup
      --spa                     use Saddlepoint approximation (SPA) for
                                p-values less than threshold
      --pThresh FLOAT(=0.05)    P-value threshold below which to apply
                                Firth/SPA correction
      --write-null-firth        store coefficients from null models with
                                approximate Firth for step 2
      --compute-all             store Firth estimates for all chromosomes
      --use-null-firth FILE     use stored coefficients for null model in
                                approximate Firth
      --chr STRING              specify chromosome to test in step 2 (use
                                for each chromosome)
      --chrList STRING,..,STRING
                                Comma separated list of chromosomes to test
                                in step 2
      --range CHR:MINPOS-MAXPOS
                                to specify a physical position window for
                                variants to test in step 2
      --sex-specific STRING     for sex-specific analyses (male/female)
      --af-cc                   print effect allele frequencies among
                                cases/controls for step 2
      --test STRING             'additive', 'dominant' or 'recessive'
                                (default is additive test)
      --htp STRING              output association files in step 2 in HTP
                                format specifying the cohort name)
      --condition-list FILE     file with list of variants to include as
                                covariates
      --condition-file FORMAT,FILE
                                optional genotype file which contains the
                                variants to include as covariates
      --condition-file-sample FILE
                                sample file accompanying BGEN file with the
                                conditional variants
      --interaction STRING      perform interaction testing with a
                                quantitative/categorical covariate
      --interaction-snp STRING  perform interaction testing with a variant
      --interaction-file FORMAT,FILE
                                optional genotype file which contains the
                                variant for GxG interaction test
      --interaction-file-sample FILE
                                sample file accompanying BGEN file with the
                                interacting variant
      --interaction-file-reffirst
                                use the first allele as the reference for
                                the BGEN or PLINK file with the interacting
                                variant [default assumes reference is last]
      --interaction-prs         perform interaction testing with the full
                                PRS from step 1
      --force-condtl            to also condition on interacting SNP in the
                                marginal GWAS test
      --no-condtl               to print out all main effects in GxE
                                interaction test
      --rare-mac FLOAT(=1000)   minor allele count (MAC) threshold below
                                which to use HLM for interaction testing
                                with QTs
      --set-list FILE           file with sets definition
      --extract-sets FILE       comma-separated list of files with IDs of
                                sets to retain in the analysis
      --exclude-sets FILE       comma-separated list of files with IDs of
                                sets to remove from the analysis
      --extract-setlist STRING  comma separated list of sets to retain in
                                the analysis
      --exclude-setlist STRING  comma separated list of sets to remove from
                                the analysis
      --anno-file FILE          file with variant annotations
      --anno-labels FILE        file with labels to annotations
      --mask-def FILE           file with mask definitions
      --aaf-file FILE           file with AAF to use when building masks
      --set-singletons          use 0/1 indicator in third column of AAF
                                file to specify singleton variants
      --aaf-bins FLOAT,..,FLOAT
                                comma separated list of AAF bins cutoffs
                                for building masks
      --build-mask STRING       rule to construct masks, can be 'max',
                                'sum' or 'comphet' (default is max)
      --vc-tests STRING,..,STRING
                                comma separated list of tests to compute
                                for each set of variants included in a mask
                                [skat/skato/skato-acat/acatv/acato]
      --vc-maxAAF FLOAT(=1)     maximum AAF for variants included in
                                gene-based tests
      --weights-col arg         column index (1-based) for user-defined
                                weights in annotation file
      --joint STRING            comma spearated list of joint tests to
                                perform
      --singleton-carrier       define singletons as variants with a single
                                carrier in the sample
      --write-mask              write masks in PLINK bed/bim/fam format
      --mask-lovo STRING        apply Leave-One-Variant-Out (LOVO) scheme
                                when building masks
                                (<set_name>,<mask_name>,<aaf_cutoff>)
      --mask-lodo STRING        apply Leave-One-Domain-Out (LODO) scheme
                                when building masks
                                (<set_name>,<mask_name>,<aaf_cutoff>)
      --skip-test               skip computing association tests after
                                building masks
      --check-burden-files      check annotation file, set list file and
                                mask file for consistency
      --strict-check-burden     to exit early if the annotation, set list
                                and mask definition files don't agree
      --force-qt                force QT run for traits with few unique
                                values
      --par-region STRING(=hg38)
                                build code to identify PAR region
                                boundaries on chrX

For more information, use option '--help' or visit the website: https://rgcgithub.github.io/regenie/

# 3. Phenotype file

One phenotype file for all ancestries. Don't worry, it shouldn't affect the actual GWAS.

For this test we will include all PD, including enriched, monogenic, etc. However for full GWAS, we should be more selective e.g. subset only to idiopathic case/control group + population control.

In [21]:
print(ANC)

FIN

In [22]:
CLINICAL_DF = pd.read_csv(
    f"{R12_DIR}/clinical_data/master_key_release12_final_vwb.csv"
).rename(columns={'GP2ID':'IID'})
CLINICAL_DF.head()

/tmp/ipykernel_1874/40050047.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  CLINICAL_DF = pd.read_csv(

,study,FID,IID,nba,wgs,clinical_exome,extended_clinical_data,nba_prune_reason,nba_label,wgs_prune_reason,...,family_history_for_qc,region_for_qc,manifest_id,genotyping_site,sample_type,amppd,flag,wgs_ploidy_estimation,variant_report,path_data_available
0,24HR,24HR_000001,24HR_000001,1.0,1.0,NaN,NaN,NaN,EUR,NaN,...,Not Reported,USA,m1,Psomagen,DNA,0.0,NaN,XX,0.0,NaN
1,24HR,24HR_000002,24HR_000002,1.0,1.0,NaN,NaN,NaN,EUR,NaN,...,Not Reported,USA,m1,Psomagen,DNA,0.0,NaN,XY,0.0,NaN
2,24HR,24HR_000003,24HR_000003,1.0,1.0,NaN,NaN,NaN,EUR,NaN,...,Not Reported,USA,m1,Psomagen,DNA,0.0,NaN,XY,0.0,NaN
3,24HR,24HR_000004,24HR_000004,1.0,1.0,NaN,NaN,NaN,EUR,NaN,...,Not Reported,USA,m1,Psomagen,DNA,0.0,NaN,XY,1.0,NaN
4,24HR,24HR_000005,24HR_000005,1.0,1.0,NaN,NaN,NaN,EUR,NaN,...,Not Reported,USA,m1,Psomagen,DNA,0.0,NaN,XY,1.0,NaN

In [23]:
CLINICAL_DF["GP2_phenotype"].value_counts()

GP2_phenotype
PD                       88340
Control                  39900
Population Control       11900
Prodromal                 7878
PSP                       2758
MSA                       1599
Other                     1241
DLB                       1069
AD                         710
CBD/CBS                    405
Mix                        315
Undetermined-MCI           264
LBD                        227
Undetermined-Dementia      140
FTD                        107
VaPD                        26
VaD                         12
Name: count, dtype: int64

In [24]:
CLINICAL_DF["GP2_PHENO"].value_counts()

GP2_PHENO
PD                                79326
Control                           37966
Population Control                11900
Affected_PD                        9014
Prodromal                          7878
PSP                                2720
Unaffected                         1934
MSA                                1580
DLB                                1060
Other                               959
AD                                  705
CBD/CBS                             400
Mix                                 306
Affected_Other                      282
Undetermined-MCI                    264
LBD                                 227
Undetermined-Dementia               139
FTD                                 106
Affected_PSP                         38
VaPD                                 26
Affected_MSA                         19
VaD                                  12
Affected_DLB                          9
Affected_Mix                          9
Affected_CBD/CBS                      5
Affected_AD                           5
Affected_FTD                          1
Affected_Undetermined-Dementia        1
Name: count, dtype: int64

In [25]:
CLINICAL_DF_nba_pruned = CLINICAL_DF[
    CLINICAL_DF['nba_prune_reason'].isna()
    & (CLINICAL_DF['nba']==1)
    & (CLINICAL_DF["GP2_PHENO"].isin(['Control','Population Control','PD','Affected_PD'])) # just do PD + Control for case/control, or PD, Control, and Population Control
]
CLINICAL_DF_nba_pruned['PD'] = 0
CLINICAL_DF_nba_pruned.loc[
    CLINICAL_DF_nba_pruned["GP2_PHENO"].isin(['PD','Affected_PD']), # same deal here
    'PD'
] = 1
print(ANC)

FIN

/tmp/ipykernel_1874/2025663080.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CLINICAL_DF_nba_pruned['PD'] = 0

In [26]:
PLINK_UNIVERSAL_PHENO = CLINICAL_DF_nba_pruned[['FID','IID','PD']]
REGENIE_UNIVERSAL_PHENO = CLINICAL_DF_nba_pruned[['FID','IID','PD']]
PLINK_UNIVERSAL_PHENO['PD'] = PLINK_UNIVERSAL_PHENO['PD']+1
print(ANC)

FIN

/tmp/ipykernel_1874/2177568461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PLINK_UNIVERSAL_PHENO['PD'] = PLINK_UNIVERSAL_PHENO['PD']+1

In [27]:
CLINICAL_DF['nba_label'].unique()
print(ANC)

FIN

For plink, remove relateds.

In [28]:

relateds = []
ANCESTRIES = CLINICAL_DF['nba_label'].unique()
ANCESTRIES = ANCESTRIES[~pd.isnull(ANCESTRIES)]
for ancestry in ANCESTRIES:
    related_temp = pd.read_csv(f'{R12_DIR}/meta_data/related_samples/{ancestry}_release12_vwb.related')
    relateds.append(related_temp)
relateds = pd.concat(relateds)

In [29]:
print(ANC)

FIN

In [30]:
PLINK_UNIVERSAL_PHENO[
    ~PLINK_UNIVERSAL_PHENO['IID'].isin(relateds['IID2'])
].shape[0]/PLINK_UNIVERSAL_PHENO[
    ~PLINK_UNIVERSAL_PHENO['IID'].isin(relateds['IID1'])
].shape[0]

0.9970667572104955

In [31]:
PLINK_UNIVERSAL_PHENO_norelated = PLINK_UNIVERSAL_PHENO[
    ~PLINK_UNIVERSAL_PHENO['IID'].isin(relateds['IID1'])
]

In [32]:
! mkdir -p data/COV_PHENO

In [33]:
PLINK_UNIVERSAL_PHENO_norelated.to_csv('data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.plink.txt', sep = '\t', index=None, na_rep = 'NA')
REGENIE_UNIVERSAL_PHENO.to_csv('data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt', sep = '\t', index=None, na_rep = 'NA')

# 4. Covariate

Covariates are: SEX, PC1-10, Genotyping sites (optional)

Same deal, single covariate file for all ancestries, but should have no affect on GWAS.

In [34]:
CLINICAL_DF_nba_pruned.tail()

,study,FID,IID,nba,wgs,clinical_exome,extended_clinical_data,nba_prune_reason,nba_label,wgs_prune_reason,...,region_for_qc,manifest_id,genotyping_site,sample_type,amppd,flag,wgs_ploidy_estimation,variant_report,path_data_available,PD
156938,YMS,YMS_000068,YMS_000068,1.0,NaN,NaN,1.0,NaN,EUR,NaN,...,USA,m2,NIH,DNA from blood,NaN,NaN,NaN,0.0,NaN,0
156939,YMS,YMS_000069,YMS_000069,1.0,NaN,NaN,1.0,NaN,EUR,NaN,...,USA,m2,NIH,DNA from blood,NaN,NaN,NaN,0.0,NaN,1
156941,YMS,YMS_000071,YMS_000071,1.0,NaN,NaN,1.0,NaN,EUR,NaN,...,USA,m2,NIH,DNA from blood,NaN,NaN,NaN,0.0,NaN,1
156945,YMS,YMS_000075,YMS_000075,1.0,NaN,NaN,1.0,NaN,EUR,NaN,...,USA,m2,NIH,DNA from blood,NaN,NaN,NaN,0.0,NaN,1
156948,YMS,YMS_000078,YMS_000078,1.0,NaN,NaN,1.0,NaN,EUR,NaN,...,USA,m3,NIH,Blood (EDTA),NaN,NaN,NaN,0.0,NaN,1

In [35]:
COV = CLINICAL_DF_nba_pruned[['FID','IID','biological_sex_for_qc','genotyping_site']]
COV = COV[['FID','IID','biological_sex_for_qc','genotyping_site']]

In [36]:
PC_ANCESTRIES = []
for ancestry in ANCESTRIES:
    PCs = pd.read_csv(f'{R12_DIR}/raw_genotypes/{ancestry}/{ancestry}_release12_vwb.eigenvec', sep = r'\s+')
    PC_ANCESTRIES.append(PCs)
PC_ANCESTRIES = pd.concat(PC_ANCESTRIES)
PC_ANCESTRIES[PC_ANCESTRIES.duplicated(subset='IID')].shape[0]

0

In [37]:
print(ANC)

FIN

In [38]:
PC_ANCESTRIES.head()

,#FID,IID,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10
0,24HR_000001,24HR_000001,0.001693,0.000683,-0.002432,-0.002203,-0.000061,-0.000458,-0.002965,-0.000632,0.001368,-0.001378
1,24HR_000002,24HR_000002,0.000633,0.005570,0.003405,0.003138,0.000075,0.005095,-0.000211,-0.003239,0.004243,-0.000791
2,24HR_000003,24HR_000003,0.001964,0.001830,-0.000801,-0.000681,0.001047,0.001566,0.002190,0.002200,-0.000910,-0.000624
3,24HR_000004,24HR_000004,-0.005769,0.001013,-0.002581,-0.000608,-0.001305,0.002956,0.000364,0.000199,-0.000450,0.000911
4,24HR_000005,24HR_000005,0.002357,-0.002457,-0.001501,-0.000811,-0.003234,0.002135,-0.001189,0.004278,0.001888,-0.000872

In [39]:
print(ANC)

FIN

In [40]:
COV_all_wPCs = COV.merge(
    PC_ANCESTRIES.drop(columns=['#FID'])
)
COV_all_wPCs.head()

,FID,IID,biological_sex_for_qc,genotyping_site,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10
0,24HR_000001,24HR_000001,Female,Psomagen,0.001693,0.000683,-0.002432,-0.002203,-0.000061,-0.000458,-0.002965,-0.000632,0.001368,-0.001378
1,24HR_000002,24HR_000002,Male,Psomagen,0.000633,0.005570,0.003405,0.003138,0.000075,0.005095,-0.000211,-0.003239,0.004243,-0.000791
2,24HR_000003,24HR_000003,Male,Psomagen,0.001964,0.001830,-0.000801,-0.000681,0.001047,0.001566,0.002190,0.002200,-0.000910,-0.000624
3,24HR_000004,24HR_000004,Male,Psomagen,-0.005769,0.001013,-0.002581,-0.000608,-0.001305,0.002956,0.000364,0.000199,-0.000450,0.000911
4,24HR_000005,24HR_000005,Male,Psomagen,0.002357,-0.002457,-0.001501,-0.000811,-0.003234,0.002135,-0.001189,0.004278,0.001888,-0.000872

In [41]:
COV_all_wPCs['biological_sex_for_qc'].unique()

array(['Female', 'Male'], dtype=object)

In [42]:
COV_all_wPCs.to_csv('data/COV_PHENO/COV_ALL_ANC_R12.txt', sep = '\t', index = None, na_rep = 'NA')

# 5. REGENIE Step 1. Ridge regression.

Ok a quick primer on Regenie. REGENIE is a two step process.

1. Step 1: Run a whole-genome regression using unimputed genotyping data. This essentially creates an offset that allows you to include related participants + increase power by residualizing whole-genome effects outside of the chromosome of analysis.
2. Step 2: Actual GWAS.

## 5a. Extract variants and samples that meet the QC criteria for Regenie Step 1

Step 1 has a more stringent QC requirement.
* MAF > 1%
* MAC > 100
* genotyping rate > 90%
* HWE 1e-15
* Autosomes only
* Exclusion of ENCODE blacklist (low complexity regions): https://github.com/Boyle-Lab/Blacklist/tree/master/lists

You can use LD pruning to reduce number of variants. Ideal range is 450k-500k. https://github.com/rgcgithub/regenie/issues/383

**You only need to DO QC STEPS ONCE per ancestry (per release)** If you need to rerun everything because of changes to phenotype, covariates, etc. don't worry about redoing QCs for step 1 file.

In [43]:
# Keep the ancestry selected in the collaborator configuration cell.
print(ANC)

FIN

In [44]:
!mkdir -p data/Regenie_step1_files
!pwd
print(f"Using blacklist: {BLACKLIST_BED}")
!ls

/home/jupyter/workspace/ws_files/MAMA_2/jf_release12/test
Using blacklist: /home/jupyter/workspace/ws_files/MAMA_2/FirstTryApril26/data/hg38-blacklist.v2.bed
chr10_FIN_release12_vwb.pvar  FIN_release12_vwb.pvar  Regenie_GWAS_EUR.ipynb
data			      output

In [45]:
EXTRACT_STEP1_VARS_CMD = f'mkdir -p data/Regenie_step1_files/{ANC}/; \
{PLINK2} --pfile "{R12_DIR}/raw_genotypes/{ANC}/{ANC}_release12_vwb" \
  --maf 0.01 --mac 100 --geno 0.1 --hwe 1e-15 \
  --autosome \
  --indep-pairwise 1000 100 0.8 \
  --exclude range "{BLACKLIST_BED}" \
  --write-snplist --write-samples \
  --out data/Regenie_step1_files/{ANC}/regenie_step1_var_inclusion'
!$EXTRACT_STEP1_VARS_CMD

PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.log.
Options in effect:
  --autosome
  --exclude range /home/jupyter/workspace/ws_files/MAMA_2/FirstTryApril26/data/hg38-blacklist.v2.bed
  --geno 0.1
  --hwe 1e-15
  --indep-pairwise 1000 100 0.8
  --mac 100
  --maf 0.01
  --out data/Regenie_step1_files/FIN/regenie_step1_var_inclusion
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb
  --write-samples
  --write-snplist

Start time: Thu Sep  3 14:25:48 2026
52195 MiB RAM detected, ~18200 available; reserving 18136 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.psam.
1824691 out of 1901389 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--exclude bed1: 5324 variants excluded.
--write-samples: Sample IDs written to
data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.id .
Calculating allele frequencies... done.
--geno: 0 variants removed due to missing genotype data.
--hwe: 17 variants removed due to Hardy-Weinberg exact test (founders only).
1581873 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
237477 variants remaining after main filters.
--write-snplist: Variant IDs written to
data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.snplist .
--indep-pairwise (7 compute threads): 84434/237477 variants removed.
Variant lists written to
data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.prune.in and
data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.prune.out .
End time: Thu Sep  3 14:25:53 2026

In [46]:
# !plink2 --pfile "{R11_DIR}/raw_genotypes//AMR_release11_vwb" \
#   --maf 0.01 --mac 100 --geno 0.1 --hwe 1e-15 0 \
#   --indep-pairwise 1000 100 0.8 \
#   --exclude range "/hg38-blacklist.v2.bed" \
#   --write-snplist --write-samples \
#   --out scratch/qc_pass_1

!wc -l scratch/qc_pass_1.prune.in

~500k variants post LD pruning, acceptable. We will proceed.

%%bash
mv scratch/qc_pass_1.prune.in data/Regenie_step1_files/R11_snps.snplist
mv scratch/qc_pass_1.id data/Regenie_step1_files/participant_list.txt

!head data/Regenie_step1_files/participant_list.txt

!mkdir data/R11_regenie_ready_genotypes/

!pwd

In [47]:
!mkdir -p data/R12_regenie_ready_genotypes

In [48]:
MAKE_FILE_CMD = f"{PLINK2} --pfile {R12_DIR}/raw_genotypes/{ANC}/{ANC}_release12_vwb \
--extract data/Regenie_step1_files/{ANC}/regenie_step1_var_inclusion.prune.in \
--keep data/Regenie_step1_files/{ANC}/regenie_step1_var_inclusion.id \
--make-pgen psam-cols=+fid --out data/R12_regenie_ready_genotypes/{ANC}_release12_vwb"
!$MAKE_FILE_CMD

PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/R12_regenie_ready_genotypes/FIN_release12_vwb.log.
Options in effect:
  --extract data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.prune.in
  --keep data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.id
  --make-pgen psam-cols=+fid
  --out data/R12_regenie_ready_genotypes/FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb

Start time: Thu Sep  3 14:26:27 2026
52195 MiB RAM detected, ~18229 available; reserving 18165 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.psam.
1901389 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/raw_genotypes/FIN/FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--extract: 153043 variants remaining.
--keep: 183 samples remaining.
183 samples (103 females, 80 males; 183 founders) remaining after main filters.
126 cases and 20 controls remaining after main filters.
153043 variants remaining after main filters.
Writing data/R12_regenie_ready_genotypes/FIN_release12_vwb.psam ... done.
Writing data/R12_regenie_ready_genotypes/FIN_release12_vwb.pvar ... done.
Writing data/R12_regenie_ready_genotypes/FIN_release12_vwb.pgen ... done.
End time: Thu Sep  3 14:26:29 2026

## 5b. Actually run step 1

After testing, it looks like Regenie generates the whole genome model off of all participants, even if some are missing in the phenotype.

So when you are preparing to run GWAS(es) or gene burden that only uses a subset of the participants, MAKE SURE TO ADD `--keep` command with the phenotype file so that it only runs the whole genome model off of the subset of the participants.

**LOOCV vs K-fold CV**

Cross-validation is necessary to prevent proximal contamination. There are two ways to do it: leave-one-out and k-fold (typically k=5).

While the performance of the two are similar, LOOCV is a bit faster with binary traits while k-fold is faster for quantitative. Use LOOCV (by adding `--loocv` option) when number of samples are < 5000 or using binary traits.

**Note on performance**

`--lowmem` has a small impact on performance, but necessary RAM can get pretty high depending on the number of phenotypes and covariates (see https://dnanexus.gitbook.io/uk-biobank-rap/science-corner/gwas-ex#benchmarking; 10 quantitative phenotypes with 3 covariates can consume ~100Gb of RAM in UKB, and binary may use more RAM). So only leave that option out if you are testing low number of phenotypes.

In [49]:
MKDIR_STEP1OUTPUT = f"mkdir -p data/Regenie_step1_output/"
!$MKDIR_STEP1OUTPUT
STEP1_CMD = f'{REGENIE} --step 1 \
  --pgen data/R12_regenie_ready_genotypes/{ANC}_release12_vwb \
  --extract data/Regenie_step1_files/{ANC}/regenie_step1_var_inclusion.prune.in \
  --keep data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --phenoFile data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --use-relative-path \
  --covarFile data/COV_PHENO/COV_ALL_ANC_R12.txt \
  --covarColList PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
  --catCovarList biological_sex_for_qc \
  --bt \
  --threads {THREADS} \
  --gz \
  --bsize 1000 \
  --lowmem \
  --loocv \
  --out data/Regenie_step1_output/GP2_R12_{ANC}_imputed'
!$STEP1_CMD

Start time: Thu Sep  3 14:26:48 2026

              |=============================|
              |      REGENIE v4.1.2.gz      |
              |=============================|

Copyright (c) 2020-2024 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : data/Regenie_step1_output/GP2_R12_FIN_imputed.log

Options in effect:
  --step 1 \
  --pgen data/R12_regenie_ready_genotypes/FIN_release12_vwb \
  --extract data/Regenie_step1_files/FIN/regenie_step1_var_inclusion.prune.in \
  --keep data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --phenoFile data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --use-relative-path \
  --covarFile data/COV_PHENO/COV_ALL_ANC_R12.txt \
  --covarColList PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
  --catCovarList biological_sex_for_qc \
  --bt \
  --threads 8 \
  --gz \
  --bsize 1000 \
  --lowmem \
  --loocv \
  --out data/Regenie_step1_output/GP2_R12_FIN_imputed

Fitting null model
 * pvar             : [data/R12_regenie_ready_genotypes/FIN_release12_vwb.pvar] n_snps = 153043
   -keeping variants specified by --extract
 * psam             : [data/R12_regenie_ready_genotypes/FIN_release12_vwb.psam] n_samples = 183
   -keeping only individuals specified by --keep
   -number of genotyped individuals remaining in the analysis = 161
 * pgen             : [data/R12_regenie_ready_genotypes/FIN_release12_vwb.pgen]
 * phenotypes       : [data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 161
 * covariates       : [data/COV_PHENO/COV_ALL_ANC_R12.txt] n_cov = 11
   -number of individuals with covariate data = 161
 * number of individuals used in analysis = 161
 * case-control counts for each trait:
   - 'PD': 137 cases and 24 controls
   -fitting null logistic regression on binary phenotypes...done (7ms)
   -residualizing and scaling phenotypes...done (0ms)
 * # threads        : [8]
 * block size       : [1000]
 * # blocks         : [162] for 153043 variants
 * # CV folds       : [161]
 * ridge data_l0    : [ 5 : 0.01 0.25 0.5 0.75 0.99 ]
 * ridge data_l1    : [ 5 : 0.01 0.25 0.5 0.75 0.99 ]
 * approximate memory usage : 2GB
 * writing level 0 predictions to disk
   -temporary files will have prefix [data/Regenie_step1_output/GP2_R12_FIN_imputed_l0_Y]
   -approximate disk space needed : 1MB
 * setting memory...done

Chromosome 1
 block [1] : 1000 snps  (3ms)
   -residualizing and scaling genotypes...done (4ms)
   -calc working matrices...done (421ms)
   -calc level 0 ridge...done (7ms)
 block [2] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (325ms)
   -calc level 0 ridge...done (5ms)
 block [3] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (253ms)
   -calc level 0 ridge...done (4ms)
 block [4] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (274ms)
   -calc level 0 ridge...done (5ms)
 block [5] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (249ms)
   -calc level 0 ridge...done (5ms)
 block [6] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (262ms)
   -calc level 0 ridge...done (5ms)
 block [7] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (288ms)
   -calc level 0 ridge...done (5ms)
 block [8] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (254ms)
   -calc level 0 ridge...done (5ms)
 block [9] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (246ms)
   -calc level 0 ridge...done (5ms)
 block [10] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (246ms)
   -calc level 0 ridge...done (5ms)
 block [11] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (285ms)
   -calc level 0 ridge...done (5ms)
 block [12] : 597 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (74ms)
   -calc level 0 ridge...done (2ms)
Chromosome 2
 block [13] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (279ms)
   -calc level 0 ridge...done (5ms)
 block [14] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (276ms)
   -calc level 0 ridge...done (5ms)
 block [15] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (276ms)
   -calc level 0 ridge...done (4ms)
 block [16] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (247ms)
   -calc level 0 ridge...done (5ms)
 block [17] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (256ms)
   -calc level 0 ridge...done (5ms)
 block [18] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (266ms)
   -calc level 0 ridge...done (4ms)
 block [19] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (252ms)
   -calc level 0 ridge...done (5ms)
 block [20] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (251ms)
   -calc level 0 ridge...done (5ms)
 block [21] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (270ms)
   -calc level 0 ridge...done (4ms)
 block [22] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (283ms)
   -calc level 0 ridge...done (5ms)
 block [23] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (259ms)
   -calc level 0 ridge...done (5ms)
 block [24] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (249ms)
   -calc level 0 ridge...done (5ms)
 block [25] : 490 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (45ms)
   -calc level 0 ridge...done (1ms)
Chromosome 3
 block [26] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (270ms)
   -calc level 0 ridge...done (5ms)
 block [27] : 1000 snps  (4ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (253ms)
   -calc level 0 ridge...done (5ms)
 block [28] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (263ms)
   -calc level 0 ridge...done (5ms)
 block [29] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (259ms)
   -calc level 0 ridge...done (6ms)
 block [30] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (295ms)
   -calc level 0 ridge...done (5ms)
 block [31] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (250ms)
   -calc level 0 ridge...done (5ms)
 block [32] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (266ms)
   -calc level 0 ridge...done (5ms)
 block [33] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (270ms)
   -calc level 0 ridge...done (4ms)
 block [34] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (248ms)
   -calc level 0 ridge...done (5ms)
 block [35] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (273ms)
   -calc level 0 ridge...done (5ms)
 block [36] : 704 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (104ms)
   -calc level 0 ridge...done (3ms)
Chromosome 4
 block [37] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (266ms)
   -calc level 0 ridge...done (4ms)
 block [38] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (317ms)
   -calc level 0 ridge...done (5ms)
 block [39] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (350ms)
   -calc level 0 ridge...done (5ms)
 block [40] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (274ms)
   -calc level 0 ridge...done (5ms)
 block [41] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (262ms)
   -calc level 0 ridge...done (5ms)
 block [42] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (319ms)
   -calc level 0 ridge...done (5ms)
 block [43] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (252ms)
   -calc level 0 ridge...done (4ms)
 block [44] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (246ms)
   -calc level 0 ridge...done (6ms)
 block [45] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (381ms)
   -calc level 0 ridge...done (5ms)
 block [46] : 900 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (225ms)
   -calc level 0 ridge...done (5ms)
Chromosome 5
 block [47] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (301ms)
   -calc level 0 ridge...done (5ms)
 block [48] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (285ms)
   -calc level 0 ridge...done (6ms)
 block [49] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (252ms)
   -calc level 0 ridge...done (5ms)
 block [50] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (280ms)
   -calc level 0 ridge...done (5ms)
 block [51] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (267ms)
   -calc level 0 ridge...done (5ms)
 block [52] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (274ms)
   -calc level 0 ridge...done (5ms)
 block [53] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (289ms)
   -calc level 0 ridge...done (5ms)
 block [54] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (281ms)
   -calc level 0 ridge...done (5ms)
 block [55] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (264ms)
   -calc level 0 ridge...done (5ms)
 block [56] : 500 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (46ms)
   -calc level 0 ridge...done (1ms)
Chromosome 6
 block [57] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (275ms)
   -calc level 0 ridge...done (6ms)
 block [58] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (2ms)
   -calc working matrices...done (264ms)
   -calc level 0 ridge...done (5ms)
 block [59] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (318ms)
   -calc level 0 ridge...done (5ms)
 block [60] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (277ms)
   -calc level 0 ridge...done (6ms)
 block [61] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (272ms)
   -calc level 0 ridge...done (5ms)
 block [62] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (349ms)
   -calc level 0 ridge...done (6ms)
 block [63] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (278ms)
   -calc level 0 ridge...done (5ms)
 block [64] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (268ms)
   -calc level 0 ridge...done (5ms)
 block [65] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (309ms)
   -calc level 0 ridge...done (5ms)
 block [66] : 630 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (86ms)
   -calc level 0 ridge...done (2ms)
Chromosome 7
 block [67] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (313ms)
   -calc level 0 ridge...done (5ms)
 block [68] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (284ms)
   -calc level 0 ridge...done (5ms)
 block [69] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (308ms)
   -calc level 0 ridge...done (5ms)
 block [70] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (264ms)
   -calc level 0 ridge...done (5ms)
 block [71] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (266ms)
   -calc level 0 ridge...done (5ms)
 block [72] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (271ms)
   -calc level 0 ridge...done (5ms)
 block [73] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (268ms)
   -calc level 0 ridge...done (5ms)
 block [74] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (284ms)
   -calc level 0 ridge...done (4ms)
 block [75] : 710 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (126ms)
   -calc level 0 ridge...done (3ms)
Chromosome 8
 block [76] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (284ms)
   -calc level 0 ridge...done (5ms)
 block [77] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (238ms)
   -calc level 0 ridge...done (4ms)
 block [78] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (255ms)
   -calc level 0 ridge...done (5ms)
 block [79] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (314ms)
   -calc level 0 ridge...done (5ms)
 block [80] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (283ms)
   -calc level 0 ridge...done (6ms)
 block [81] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (339ms)
   -calc level 0 ridge...done (5ms)
 block [82] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (283ms)
   -calc level 0 ridge...done (6ms)
 block [83] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (262ms)
   -calc level 0 ridge...done (6ms)
 block [84] : 211 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (7ms)
   -calc level 0 ridge...done (1ms)
Chromosome 9
 block [85] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (265ms)
   -calc level 0 ridge...done (5ms)
 block [86] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (297ms)
   -calc level 0 ridge...done (5ms)
 block [87] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (262ms)
   -calc level 0 ridge...done (5ms)
 block [88] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (265ms)
   -calc level 0 ridge...done (4ms)
 block [89] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (269ms)
   -calc level 0 ridge...done (5ms)
 block [90] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (239ms)
   -calc level 0 ridge...done (5ms)
 block [91] : 988 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (255ms)
   -calc level 0 ridge...done (5ms)
Chromosome 10
 block [92] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (273ms)
   -calc level 0 ridge...done (6ms)
 block [93] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (256ms)
   -calc level 0 ridge...done (5ms)
 block [94] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (250ms)
   -calc level 0 ridge...done (6ms)
 block [95] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (261ms)
   -calc level 0 ridge...done (4ms)
 block [96] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (263ms)
   -calc level 0 ridge...done (5ms)
 block [97] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (246ms)
   -calc level 0 ridge...done (5ms)
 block [98] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (272ms)
   -calc level 0 ridge...done (6ms)
 block [99] : 689 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (114ms)
   -calc level 0 ridge...done (3ms)
Chromosome 11
 block [100] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (287ms)
   -calc level 0 ridge...done (6ms)
 block [101] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (270ms)
   -calc level 0 ridge...done (5ms)
 block [102] : 1000 snps  (2ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (270ms)
   -calc level 0 ridge...done (6ms)
 block [103] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (331ms)
   -calc level 0 ridge...done (5ms)
 block [104] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (288ms)
   -calc level 0 ridge...done (6ms)
 block [105] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (248ms)
   -calc level 0 ridge...done (4ms)
 block [106] : 1000 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (288ms)
   -calc level 0 ridge...done (5ms)
 block [107] : 504 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (44ms)
   -calc level 0 ridge...done (1ms)
Chromosome 12
 block [108] : 1000 snps  (1ms)

Step 1 took only 445.611s seconds. Expect slower as sample size gets larger (UKB can take hours).

# 6. Step 2 - actual GWAS

REGENIE doesn't have MAF filter, only MAC.

For test, we will only look at INFO > 0.6

In [50]:
MAC = np.floor((899+628)*0.01)
MAC

15.0

In [51]:
### ASK ABOUT WHY THIS MAC

In [53]:
print(ANC)

FIN

In [54]:
CMD1 = f'mkdir -p data/symlink_R12_{ANC}; \
ln -s $(realpath {R12_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release12_vwb.'
CMD2 = '{pvar,pgen}) '
CMD3 = f'data/symlink_R12_{ANC}/'
SYMLINK_CMD = CMD1+CMD2+CMD3
!$SYMLINK_CMD

# CMD1 = f'mkdir -p data/symlink_R11_{ANC}; \
# ln -s $(realpath {R11_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release11_vwb.'
# CMD2 = '{pvar,pgen}) '
# CMD3 = f'data/symlink_R11_{ANC}/'
# SYMLINK_CMD = CMD1+CMD2+CMD3
# !bash ls "$SYMLINK_CMD"

# SYMLINK_CMD = (
#     f"mkdir -p data/symlink_R11_{ANC}; "
#     f"ln -s $(realpath {R11_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release11_vwb.{{pvar,pgen}}) "
#     f"data/symlink_R11_{ANC}/"
# )

# print(SYMLINK_CMD)
# !bash -lc "$SYMLINK_CMD"

In [56]:
for CHRNUM in CHROMOSOMES:
    CMD = f'{PLINK2} --pfile {R12_DIR}/imputed_genotypes/{ANC}/chr{CHRNUM}_{ANC}_release12_vwb \
    --write-snplist \
    --make-just-psam cols=+fid --out data/symlink_R12_{ANC}/chr{CHRNUM}_{ANC}_release12_vwb'
    !$CMD

PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr1_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr1_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:13 2026
52195 MiB RAM detected, ~18181 available; reserving 18117 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.psam.
1079262 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr1_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr1_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr1_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:15 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr2_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr2_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:16 2026
52195 MiB RAM detected, ~18147 available; reserving 18083 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.psam.
1161330 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr2_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr2_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr2_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:17 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr3_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr3_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:19 2026
52195 MiB RAM detected, ~18156 available; reserving 18092 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.psam.
973595 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr3_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr3_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr3_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:20 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr4_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr4_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:22 2026
52195 MiB RAM detected, ~18152 available; reserving 18088 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.psam.
987128 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr4_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr4_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr4_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:23 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr5_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr5_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:24 2026
52195 MiB RAM detected, ~18156 available; reserving 18092 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.psam.
893931 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr5_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr5_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr5_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:26 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr6_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr6_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:27 2026
52195 MiB RAM detected, ~18149 available; reserving 18085 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.psam.
891266 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr6_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr6_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr6_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:28 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr7_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr7_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:30 2026
52195 MiB RAM detected, ~18146 available; reserving 18082 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.psam.
798427 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr7_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr7_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr7_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:31 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr8_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr8_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:32 2026
52195 MiB RAM detected, ~18156 available; reserving 18092 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.psam.
754331 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr8_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr8_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr8_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:33 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr9_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr9_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:35 2026
52195 MiB RAM detected, ~18141 available; reserving 18077 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.psam.
590093 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr9_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr9_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr9_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:35 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr10_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr10_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:37 2026
52195 MiB RAM detected, ~18147 available; reserving 18083 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb.psam.
692560 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr10_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr10_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr10_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:38 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr11_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr11_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:40 2026
52195 MiB RAM detected, ~18122 available; reserving 18058 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.psam.
671250 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr11_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr11_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr11_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:41 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr12_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr12_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:42 2026
52195 MiB RAM detected, ~18155 available; reserving 18091 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.psam.
657130 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr12_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr12_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr12_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:43 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr13_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr13_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:45 2026
52195 MiB RAM detected, ~18141 available; reserving 18077 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.psam.
504455 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr13_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr13_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr13_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:45 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr14_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr14_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:47 2026
52195 MiB RAM detected, ~18155 available; reserving 18091 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.psam.
444435 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr14_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr14_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr14_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:48 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr15_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr15_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:49 2026
52195 MiB RAM detected, ~18154 available; reserving 18090 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.psam.
391883 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr15_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr15_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr15_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:50 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr16_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr16_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:51 2026
52195 MiB RAM detected, ~18136 available; reserving 18072 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.psam.
425046 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr16_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr16_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr16_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:52 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr17_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr17_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:53 2026
52195 MiB RAM detected, ~18147 available; reserving 18083 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.psam.
373594 variants loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr17_FIN_release12_vwb.pvar.
1 binary phenotype loaded (126 cases, 20 controls).
--write-snplist: Variant IDs written to
data/symlink_R12_FIN/chr17_FIN_release12_vwb.snplist .
Writing data/symlink_R12_FIN/chr17_FIN_release12_vwb.psam ... done.
End time: Thu Sep  3 14:33:54 2026
PLINK v2.0.0-a.6.9LM 64-bit Intel (29 Jan 2025)    cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/symlink_R12_FIN/chr18_FIN_release12_vwb.log.
Options in effect:
  --make-just-psam cols=+fid
  --out data/symlink_R12_FIN/chr18_FIN_release12_vwb
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb
  --write-snplist

Start time: Thu Sep  3 14:33:56 2026
52195 MiB RAM detected, ~18152 available; reserving 18088 MiB for main
workspace.
Using up to 8 compute threads.
183 samples (103 females, 80 males; 183 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release12/imputed_genotypes/FIN/chr18_FIN_release12_vwb.psam.
393015 variants loaded from

In [61]:
MKDIR_CMD = f'mkdir -p output/Regenie_GWAS/{ANC}_R12_imputed/'
!$MKDIR_CMD

In [62]:
### For this step use 16 CPUs

In [63]:
for CHRNUM in STEP2_CHROMOSOMES:
    CMD = f'{REGENIE} --step 2 \
      --pred data/Regenie_step1_output/GP2_R12_{ANC}_imputed_pred.list \
      --pgen "data/symlink_R12_{ANC}/chr{CHRNUM}_{ANC}_release12_vwb" \
      --keep data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
      --phenoFile data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
      --use-relative-path \
      --covarFile data/COV_PHENO/COV_ALL_ANC_R12.txt \
      --covarColList PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
      --catCovarList biological_sex_for_qc \
      --minMAC {MAC} \
      --minINFO 0.6 \
      --bt \
      --af-cc \
      --threads {THREADS} \
      --firth --firth-se --approx \
      --gz \
      --bsize 200 \
      --out output/Regenie_GWAS/{ANC}_R12_imputed/{CHRNUM}'
    !$CMD
    

SYMLINK_CMD = (
    f"mkdir -p data/symlink_R12_{ANC}; "
    f"ln -s $(realpath {R12_DIR}/imputed_genotypes/{ANC}/chr*_{ANC}_release12_vwb.{{pvar,pgen}}) "
    f"data/symlink_R12_{ANC}/"
)

print(SYMLINK_CMD)
!bash -lc "$SYMLINK_CMD"

Start time: Thu Sep  3 14:34:29 2026

              |=============================|
              |      REGENIE v4.1.2.gz      |
              |=============================|

Copyright (c) 2020-2024 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : output/Regenie_GWAS/FIN_R12_imputed/1.log

Options in effect:
  --step 2 \
  --pred data/Regenie_step1_output/GP2_R12_FIN_imputed_pred.list \
  --pgen data/symlink_R12_FIN/chr1_FIN_release12_vwb \
  --keep data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --phenoFile data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt \
  --use-relative-path \
  --covarFile data/COV_PHENO/COV_ALL_ANC_R12.txt \
  --covarColList PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
  --catCovarList biological_sex_for_qc \
  --minMAC 15.0 \
  --minINFO 0.6 \
  --bt \
  --af-cc \
  --threads 8 \
  --firth \
  --firth-se \
  --approx \
  --gz \
  --bsize 200 \
  --out output/Regenie_GWAS/FIN_R12_imputed/1

Association testing mode with fast multithreading using OpenMP
 * pvar             : [data/symlink_R12_FIN/chr1_FIN_release12_vwb.pvar] n_snps = 1079262
 * psam             : [data/symlink_R12_FIN/chr1_FIN_release12_vwb.psam] n_samples = 183
   -keeping only individuals specified by --keep
   -number of genotyped individuals remaining in the analysis = 161
 * pgen             : [data/symlink_R12_FIN/chr1_FIN_release12_vwb.pgen]
 * phenotypes       : [data/COV_PHENO/GP2_R12_ALLANC_PD_PHENO.regenie.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 161
 * covariates       : [data/COV_PHENO/COV_ALL_ANC_R12.txt] n_cov = 11
   -number of individuals with covariate data = 161
 * number of individuals used in analysis = 161
 * case-control counts for each trait:
   - 'PD': 137 cases and 24 controls
 * LOCO predictions : [data/Regenie_step1_output/GP2_R12_FIN_imputed_pred.list]
   -file [data/Regenie_step1_output/GP2_R12_FIN_imputed_1.loco.gz] for phenotype 'PD'
 * # threads        : [8]
 * block size       : [200]
 * # blocks         : [5397]
 * approximate memory usage : 251MB
 * using minimum MAC of 15 (variants with lower MAC are ignored)
 * using minimum imputation info score of 0.6 (variants with lower info score are ignored)
 * using fast Firth correction for logistic/cox regression p-values less than 0.05
    - using back-correction to compute Firth SE

Chromosome 1 [5397 blocks in total]
   -reading loco predictions for the chromosome...done (1ms)
   -fitting null logistic regression on binary phenotypes...done (0ms)
   -fitting null Firth logistic regression on binary phenotypes...done (24ms)
 block [1/5397] : done (161ms)
 block [2/5397] : done (38ms)
 block [3/5397] : done (0ms)
 block [4/5397] : done (51ms)
 block [5/5397] : done (0ms)
 block [6/5397] : done (55ms)
 block [7/5397] : done (0ms)
 block [8/5397] : done (0ms)
 block [9/5397] : done (55ms)
 block [10/5397] : done (0ms)
 block [11/5397] : done (2ms)
 block [12/5397] : done (0ms)
 block [13/5397] : done (64ms)
 block [14/5397] : done (0ms)
 block [15/5397] : done (2ms)
 block [16/5397] : done (0ms)
 block [17/5397] : done (56ms)
 block [18/5397] : done (3ms)
 block [19/5397] : done (63ms)
 block [20/5397] : done (1ms)
 block [21/5397] : done (47ms)
 block [22/5397] : done (2ms)
 block [23/5397] : done (117ms)
 block [24/5397] : done (0ms)
 block [25/5397] : done (56ms)
 block [26/5397] : done (1ms)
 block [27/5397] : done (1ms)
 block [28/5397] : done (0ms)
 block [29/5397] : done (40ms)
 block [30/5397] : done (1ms)
 block [31/5397] : done (42ms)
 block [32/5397] : done (0ms)
 block [33/5397] : done (44ms)
 block [34/5397] : done (0ms)
 block [35/5397] : done (0ms)
 block [36/5397] : done (0ms)
 block [37/5397] : done (52ms)
 block [38/5397] : done (1ms)
 block [39/5397] : done (0ms)
 block [40/5397] : done (0ms)
 block [41/5397] : done (55ms)
 block [42/5397] : done (0ms)
 block [43/5397] : done (0ms)
 block [44/5397] : done (1ms)
 block [45/5397] : done (0ms)
 block [46/5397] : done (1ms)
 block [47/5397] : done (3ms)
 block [48/5397] : done (0ms)
 block [49/5397] : done (1ms)
 block [50/5397] : done (0ms)
 block [51/5397] : done (0ms)
 block [52/5397] : done (56ms)
 block [53/5397] : done (0ms)
 block [54/5397] : done (0ms)
 block [55/5397] : done (0ms)
 block [56/5397] : done (1ms)
 block [57/5397] : done (0ms)
 block [58/5397] : done (0ms)
 block [59/5397] : done (1ms)
 block [60/5397] : done (0ms)
 block [61/5397] : done (0ms)
 block [62/5397] : done (1ms)
 block [63/5397] : done (0ms)
 block [64/5397] : done (46ms)
 block [65/5397] : done (0ms)
 block [66/5397] : done (41ms)
 block [67/5397] : done (1ms)
 block [68/5397] : done (1ms)
 block [69/5397] : done (41ms)
 block [70/5397] : done (1ms)
 block [71/5397] : done (1ms)
 block [72/5397] : done (0ms)
 block [73/5397] : done (0ms)
 block [74/5397] : done (47ms)
 block [75/5397] : done (1ms)
 block [76/5397] : done (1ms)
 block [77/5397] : done (0ms)
 block [78/5397] : done (0ms)
 block [79/5397] : done (72ms)
 block [80/5397] : done (0ms)
 block [81/5397] : done (65ms)
 block [82/5397] : done (1ms)
 block [83/5397] : done (1ms)
 block [84/5397] : done (1ms)
 block [85/5397] : done (1ms)
 block [86/5397] : done (77ms)
 block [87/5397] : done (0ms)
 block [88/5397] : done (48ms)
 block [89/5397] : done (0ms)
 block [90/5397] : done (48ms)
 block [91/5397] : done (1ms)
 block [92/5397] : done (1ms)
 block [93/5397] : done (1ms)
 block [94/5397] : done (38ms)
 block [95/5397] : done (1ms)
 block [96/5397] : done (2ms)
 block [97/5397] : done (1ms)
 block [98/5397] : done (1ms)
 block [99/5397] : done (0ms)
 block [100/5397] : done (0ms)
 block [101/5397] : done (0ms)
 block [102/5397] : done (53ms)
 block [103/5397] : done (0ms)
 block [104/5397] : done (1ms)
 block [105/5397] : done (1ms)
 block [106/5397] : done (0ms)
 block [107/5397] : done (1ms)
 block [108/5397] : done (1ms)
 block [109/5397] : done (0ms)
 block [110/5397] : done (1ms)
 block [111/5397] : done (0ms)
 block [112/5397] : done (49ms)
 block [113/5397] : done (1ms)
 block [114/5397] : done (1ms)
 block [115/5397] : done (78ms)
 block [116/5397] : done (0ms)
 block [117/5397] : done (1ms)
 block [118/5397] : done (57ms)
 block [119/5397] : done (1ms)
 block [120/5397] : done (1ms)
 block [121/5397] : done (1ms)
 block [122/5397] : done (44ms)
 block [123/5397] : done (1ms)
 block [124/5397] : done (0ms)
 block [125/5397] : done (0ms)
 block [126/5397] : done (1ms)
 block [127/5397] : done (0ms)
 block [128/5397] : done (0ms)
 block [129/5397] : done (1ms)
 block [130/5397] : done (0ms)
 block [131/5397] : done (0ms)
 block [132/5397] : done (1ms)
 block [133/5397] : done (0ms)
 block [134/5397] : done (0ms)
 block [135/5397] : done (60ms)
 block [136/5397] : done (0ms)
 block [137/5397] : done (0ms)
 block [138/5397] : done (56ms)
 block [139/5397] : done (1ms)
 block [140/5397] : done (0ms)
 block [141/5397] : done (2ms)
 block [142/5397] : done (0ms)
 block [143/5397] : done (0ms)
 block [144/5397] : done (44ms)
 block [145/5397] : done (0ms)
 block [146/5397] : done (0ms)
 block [147/5397] : done (45ms)
 block [148/5397] : done (0ms)
 block [149/5397] : done (1ms)
 block [150/5397] : done (0ms)
 block [151/5397] : done (0ms)
 block [152/5397] : done (50ms)
 block [153/5397] : done (0ms)
 block [154/5397] : done (0ms)
 block [155/5397] : done (1ms)
 block [156/5397] : done (0ms)
 block [157/5397] : done (1ms)
 block [158/5397] : done (0ms)
 block [159/5397] : done (1ms)
 block [160/5397] : done (0ms)
 block [161/5397] : done (1ms)
 block [162/5397] : done (60ms)
 block [163/5397] : done (1ms)
 block [164/5397] : done (1ms)
 block [165/5397] : done (60ms)
 block [166/5397] : done (0ms)
 block [167/5397] : done (1ms)
 block [168/5397] : done (1ms)
 block [169/5397] : done (0ms)
 block [170/5397] : done (42ms)
 block [171/5397] : done (0ms)
 block [172/5397] : done (44ms)
 block [173/5397] : done (0ms)
 block [174/5397] : done (0ms)
 block [175/5397] : done (2ms)
 block [176/5397] : done (0ms)
 block [177/5397] : done (0ms)
 block [178/5397] : done (0ms)
 block [179/5397] : done (1ms)
 block [180/5397] : done (0ms)
 block [181/5397] : done (0ms)
 block [182/5397] : done (0ms)
 block [183/5397] : done (1ms)
 block [184/5397] : done (0ms)
 block [185/5397] : done (0ms)
 block [186/5397] : done (0ms)
 block [187/5397] : done (0ms)
 block [188/5397] : done (53ms)
 block [189/5397] : done (1ms)
 block [190/5397] : done (1ms)
 block [191/5397] : done (1ms)
 block [192/5397] : done (2ms)
 block [193/5397] : done (0ms)
 block [194/5397] : done (41ms)
 block [195/5397] : done (3ms)
 block [196/5397] : done (50ms)
 block [197/5397] : done (0ms)
 block [198/5397] : done (0ms)
 block [199/5397] : done (1ms)
 block [200/5397] : done (0ms)
 block [201/5397] : done (0ms)
 block [202/5397] : done (58ms)
 block [203/5397] : done (0ms)
 block [204/5397] : done (0ms)
 block [205/5397] : done (19ms)
 block [206/5397] : done (0ms)
 block [207/5397] : done (0ms)
 block [208/5397] : done (46ms)
 block [209/5397] : done (0ms)
 block [210/5397] : done (0ms)
 block [211/5397] : done (0ms)
 block [212/5397] : done (1ms)
 block [213/5397] : done (0ms)
 block [214/5397] : done (0ms)
 block [215/5397] : done (1ms)
 block [216/5397] : done (2ms)
 block [217/5397] : done (54ms)
 block [218/5397] : done (0ms)
 block [219/5397] : done (0ms)
 block [220/5397] : done (75ms)
 block [221/5397] : done (0ms)
 block [222/5397] : done (0ms)
 block [223/5397] : done (0ms)
 block [224/5397] : done (50ms)
 block [225/5397] : done (0ms)
 block [226/5397] : done (0ms)
 block [227/5397] : done (0ms)
 block [228/5397] : done (60ms)
 block [229/5397] : done (0ms)
 block [230/5397] : done (0ms)
 block [231/5397] : done (1ms)
 block [232/5397] : done (0ms)
 block [233/5397] : done (1ms)
 block [234/5397] : done (0ms)
 block [235/5397] : done (0ms)
 block [236/5397] : done (1ms)
 block [237/5397] : done (0ms)
 block [238/5397] : done (0ms)
 block [239/5397] : done (42ms)
 block [240/5397] : done (0ms)
 block [241/5397] : done (0ms)
 block [242/5397] : done (1ms)
 block [243/5397] : done (1ms)
 block [244/5397] : done (1ms)
 block [245/5397] : done (4ms)
 block [246/5397] : done (1ms)
 block [247/5397] : done (0ms)
 block [248/5397] : done (55ms)
 block [249/5397] : done (0ms)
 block [250/5397] : done (0ms)
 block [251/5397] : done (44ms)
 block [252/5397] : done (0ms)
 block [253/5397] : done (0ms)
 block [254/5397] : done (0ms)
 block [255/5397] : done (0ms)
 block [256/5397] : done (53ms)
 block [257/5397] : done (0ms)
 block [258/5397] : done (1ms)
 block [259/5397] : done (0ms)
 block [260/5397] : done (0ms)
 block [261/5397] : done (0ms)
 block [262/5397] : done (1ms)
 block [263/5397] : done (0ms)
 block [264/5397] : done (0ms)
 block [265/5397] : done (0ms)
 block [266/5397] : done (1ms)
 block [267/5397] : done (0ms)
 block [268/5397] : done (1ms)
 block [269/5397] : done (1ms)
 block [270/5397] : done (0ms)
 block [271/5397] : done (0ms)
 block [272/5397] : done (135ms)
 block [273/5397] : done (0ms)
 block [274/5397] : done (0ms)
 block [275/5397] : done (1ms)
 block [276/5397] : done (2ms)
 block [277/5397] : done (0ms)
 block [278/5397] : done (0ms)
 block [279/5397] : done (67ms)
 block [280/5397] : done (0ms)
 block [281/5397] : done (1ms)
 block [282/5397] : done (1ms)
 block [283/5397] : done (0ms)
 block [284/5397] : done (1ms)
 block [285/5397] : done (0ms)
 block [286/5397] : done (47ms)
 block [287/5397] : done (0ms)
 block [288/5397] : done (0ms)
 block [289/5397] : done (54ms)
 block [290/5397] : done (0ms)
 block [291/5397] : done (55ms)
 block [292/5397] : done (0ms)
 block [293/5397] : done (0ms)
 block [294/5397] : done (48ms)
 block [295/5397] : done (0ms)
 block [296/5397] : done (1ms)
 block [297/5397] : done (1ms)
 block [298/5397] : done (0ms)
 block [299/5397] : done (1ms)
 block [300/5397] : done (0ms)
 block [301/5397] : done (0ms)
 block [302/5397] : done (39ms)
 block [303/5397] : done (44ms)
 block [304/5397] : done (1ms)
 block [305/5397] : done (1ms)
 block [306/5397] : done (39ms)
 block [307/5397] : done (1ms)
 block [308/5397] : done (0ms)
 block [309/5397] : done (1ms)
 block [310/5397] : done (0ms)
 block [311/5397] : done (0ms)
 block [312/5397] : done (1ms)
 block [313/5397] : done (0ms)
 block [314/5397] : done (0ms)
 block [315/5397] : done (120ms)
 block [316/5397] : done (1ms)
 block [317/5397] : done (1ms)
 block [318/5397] : done (0ms)
 block [319/5397] : done (57ms)
 block [320/5397] : done (0ms)
 block [321/5397] : done (0ms)
 block [322/5397] : done (56ms)
 block [323/5397] : done (0ms)
 block [324/5397] : done (0ms)
 block [325/5397] : done (1ms)
 block [326/5397] : done (0ms)
 block [327/5397] : done (54ms)
 block [328/5397] : done (0ms)
 block [329/5397] : done (2ms)
 block [330/5397] : done (0ms)
 block [331/5397] : done (1ms)
 block [332/5397] : done (1ms)
 block [333/5397] : done (64ms)
 block [334/5397] : done (1ms)
 block [335/5397] : done (0ms)
 block [336/5397] : done (54ms)
 block [337/5397] : done (0ms)
 block [338/5397] : done (0ms)
 block [339/5397] : done (50ms)
 block [340/5397] : done (1ms)
 block [341/5397] : done (1ms)
 block [342/5397] : done (0ms)
 block [343/5397] : done (0ms)
 block [344/5397] : done (0ms)
 block [345/5397] : done (68ms)
 block [346/5397] : done (0ms)
 block [347/5397] : done (0ms)
 block [348/5397] : done (0ms)
 block [349/5397] : done (152ms)
 block [350/5397] : done (0ms)
 block [351/5397] : done (0ms)
 block [352/5397] : done (37ms)
 block [353/5397] : done (0ms)
 block [354/5397] : done (0ms)
 block [355/5397] : done (0ms)
 block [356/5397] : done (1ms)
 block [357/5397] : done (2ms)
 block [358/5397] : done (1ms)
 block [359/5397] : done (56ms)
 block [360/5397] : done (3ms)
 block [361/5397] : done (2ms)
 block [362/5397] : done (0ms)
 block [363/5397] : done (57ms)
 block [364/5397] : done (1ms)
 block [365/5397] : done (1ms)
 block [366/5397] : done (1ms)
 block [367/5397] : done (1ms)
 block [368/5397] : done (1ms)
 block [369/5397] : done (1ms)
 block [370/5397] : done (1ms)
 block [371/5397] : done (1ms)
 block [372/5397] : done (1ms)
 block [373/5397] : done (3ms)
 block [374/5397] : done (1ms)
 block [375/5397] : done (38ms)
 block [376/5397] : done (3ms)
 block [377/5397] : done (53ms)
 block [378/5397] : done (1ms)
 block [379/5397] : done (2ms)
 block [380/5397] : done (1ms)
 block [381/5397] : done (1ms)
 block [382/5397] : done (1ms)
 block [383/5397] : done (44ms)
 block [384/5397] : done (0ms)
 block [385/5397] : done (0ms)
 block [386/5397] : done (36ms)
 block [387/5397] : done (1ms)
 block [388/5397] : done (59ms)
 block [389/5397] : done (1ms)
 block [390/5397] : done (1ms)
 block [391/5397] : done (3ms)
 block [392/5397] : done (1ms)
 block [393/5397] : done (86ms)
 block [394/5397] : done (1ms)
 block [395/5397] : done (1ms)
 block [396/5397] : done (0ms)
 block [397/5397] : done (1ms)
 block [398/5397] : done (1ms)
 block [399/5397] : done (2ms)
 block [400/5397] : done (71ms)
 block [401/5397] : done (1ms)
 block [402/5397] : done (0ms)
 block [403/5397] : done (1ms)
 block [404/5397] : done (0ms)
 block [405/5397] : done (0ms)
 block [406/5397] : done (49ms)
 block [407/5397] : done (0ms)
 block [408/5397] : done (0ms)
 block [409/5397] : done (0ms)
 block [410/5397] : done (42ms)
 block [411/5397] : done (1ms)
 block [412/5397] : done (3ms)
 block [413/5397] : done (1ms)
 block [414/5397] : done (1ms)
 block [415/5397] : done (65ms)
 block [416/5397] : done (0ms)
 block [417/5397] : done (0ms)
 block [418/5397] : done (1ms)
 block [419/5397] : done (0ms)
 block [420/5397] : done (0ms)
 block [421/5397] : done (1ms)
 block [422/5397] : done (0ms)
 block [423/5397] : done (0ms)
 block [424/5397] : done (1ms)
 block [425/5397] : done (0ms)
 block [426/5397] : done (1ms)
 block [427/5397] : done (0ms)
 block [428/5397] : done (1ms)
 block [429/5397] : done (1ms)
 block [430/5397] : done (61ms)
 block [431/5397] : done (0ms)
 block [432/5397] : done (1ms)
 block [433/5397] : done (1ms)
 block [434/5397] : done (1ms)
 block [435/5397] : done (1ms)
 block [436/5397] : done (52ms)
 block [437/5397] : done (1ms)
 block [438/5397] : done (1ms)
 block [439/5397] : done (53ms)
 block [440/5397] : done (1ms)
 block [441/5397] : done (0ms)
 block [442/5397] : done (74ms)
 block [443/5397] : done (1ms)
 block [444/5397] : done (0ms)
 block [445/5397] : done (65ms)
 block [446/5397] : done (0ms)
 block [447/5397] : done (1ms)
 block [448/5397] : done (91ms)
 block [449/5397] : done (0ms)
 block [450/5397] : done (1ms)
 block [451/5397] : done (1ms)
 block [452/5397] : done (1ms)
 block [453/5397] : done (54ms)
 block [454/5397] : done (0ms)
 block [455/5397] : done (1ms)
 block [456/5397] : done (1ms)
 block [457/5397] : done (2ms)
 block [458/5397] : done (0ms)
 block [459/5397] : done (1ms)
 block [460/5397] : done (0ms)
 block [461/5397] : done (0ms)
 block [462/5397] : done (64ms)
 block [463/5397] : done (0ms)
 block [464/5397] : done (2ms)
 block [465/5397] : done (56ms)
 block [466/5397] : done (0ms)
 block [467/5397] : done (2ms)
 block [468/5397] : done (1ms)
 block [469/5397] : done (1ms)
 block [470/5397] : done (1ms)
 block [471/5397] : done (40ms)
 block [472/5397] : done (1ms)
 block [473/5397] : done (0ms)
 block [474/5397] : done (3ms)
 block [475/5397] : done (0ms)
 block [476/5397] : done (0ms)
 block [477/5397] : done (1ms)
 block [478/5397] : done (0ms)
 block [479/5397] : done (1ms)
 block [480/5397] : done (1ms)
 block [481/5397] : done (1ms)
 block [482/5397] : done (1ms)
 block [483/5397] : done (1ms)
 block [484/5397] : done (43ms)
 block [485/5397] : done (0ms)
 block [486/5397] : done (0ms)
 block [487/5397] : done (43ms)
 block [488/5397] : done (0ms)
 block [489/5397] : done (0ms)
 block [490/5397] : done (0ms)
 block [491/5397] : done (0ms)
 block [492/5397] : done (219ms)
 block [493/5397] : done (0ms)
 block [494/5397] : done (0ms)
 block [495/5397] : done (0ms)
 block [496/5397] : done (1ms)
 block [497/5397] : done (0ms)
 block [498/5397] : done (0ms)
 block [499/5397] : done (0ms)
 block [500/5397] : done (1ms)
 block [501/5397] : done (3ms)
 block [502/5397] : done (0ms)
 block [503/5397] : done (1ms)
 block [504/5397] : done (0ms)
 block [505/5397] : done (0ms)
 block [506/5397] : done (0ms)
 block [507/5397] : done (66ms)
 block [508/5397] : done (0ms)
 block [509/5397] : done (1ms)
 block [510/5397] : done (1ms)
 block [511/5397] : done (2ms)
 block [512/5397] : done (58ms)
 block [513/5397] : done (0ms)
 block [514/5397] : done (1ms)
 block [515/5397] : done (1ms)
 block [516/5397] : done (0ms)
 block [517/5397] : done (0ms)
 block [518/5397] : done (1ms)
 block [519/5397] : done (0ms)
 block [520/5397] : done (1ms)
 block [521/5397] : done (0ms)
 block [522/5397] : done (0ms)
 block [523/5397] : done (48ms)
 block [524/5397] : done (0ms)
 block [525/5397] : done (0ms)
 block [526/5397] : done (69ms)
 block [527/5397] : done (0ms)
 block [528/5397] : done (0ms)
 block [529/5397] : done (0ms)
 block [530/5397] : done (46ms)
 block [531/5397] : done (0ms)
 block [532/5397] : done (0ms)
 block [533/5397] : done (43ms)
 block [534/5397] : done (1ms)
 block [535/5397] : done (0ms)
 block [536/5397] : done (1ms)
 block [537/5397] : done (0ms)
 block [538/5397] : done (0ms)
 block [539/5397] : done (0ms)
 block [540/5397] : done (0ms)
 block [541/5397] : done (135ms)
 block [542/5397] : done (0ms)
 block [543/5397] : done (0ms)
 block [544/5397] : done (0ms)
 block [545/5397] : done (1ms)
 block [546/5397] : done (1ms)
 block [547/5397] : done (0ms)
 block [548/5397] : done (1ms)
 block [549/5397] : done (1ms)
 block [550/5397] : done (1ms)
 block [551/5397] : done (0ms)
 block [552/5397] : done (0ms)
 block [553/5397] : done (0ms)
 block [554/5397] : done (39ms)

In [64]:
def fix_regenie_output(df):
    df['A1FREQ_CONTROLS'] = (
        (df['A1FREQ']*df['N']-df['A1FREQ_CASES']*df['N_CASES'])
        /df['N_CONTROLS'])
    df['P'] = np.power(10,-df['LOG10P'])
    return(df)

def read_regenie_output(path, gene_level=False):
    if gene_level:
        DF = pd.read_csv(path, sep = ' ', skiprows=1)
    else:
        DF = pd.read_csv(path, sep = ' ')
    DF = fix_regenie_output(DF)
    return(DF)

Only issue with REGENIE right now - their "A1FREQ_CONTROLS" column is bugged. Older versions don't have this bug, but they're also slower. We can fix this easily by reading the outputs with the functions above.

In [65]:
GWAS_RES = []
for CHRNUM in CHROMOSOMES:
    TEMP = read_regenie_output(
        f"output/Regenie_GWAS/{ANC}_R12_imputed/{CHRNUM}_PD.regenie.gz"
    )
    GWAS_RES.append(TEMP)

In [66]:
GWAS_RES = pd.concat(GWAS_RES)
GWAS_RES.to_csv(
    f"output/Regenie_GWAS/{ANC}_R12_imputed/FULL_{ANC}_GWAS_PD.regenie.gz",
    sep = '\t',
    index = None,
    na_rep = 'NA'
)
GWAS_RES.sort_values(by='P')

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,A1FREQ_CASES,A1FREQ_CONTROLS,INFO,N,N_CASES,N_CONTROLS,TEST,BETA,SE,CHISQ,LOG10P,EXTRA,P
242910,8,108017070,chr8:108017070:G:C,G,C,0.186900,0.142204,0.442040,0.862259,161,137,24,ADD,-1.901000e+00,0.493529,1.483680e+01,3.930980e+00,NaN,0.000117
61953,22,45880448,chr22:45880448:T:G,T,G,0.388108,0.340277,0.661143,1.102930,161,137,24,ADD,-1.301440e+00,0.366170,1.263230e+01,3.421200e+00,NaN,0.000379
242894,8,108008602,chr8:108008602:A:C,A,C,0.288820,0.244526,0.541665,0.986993,161,137,24,ADD,-1.325880e+00,0.379152,1.222860e+01,3.327330e+00,NaN,0.000471
242895,8,108008782,chr8:108008782:A:C,A,C,0.287426,0.244037,0.535105,0.969582,161,137,24,ADD,-1.338090e+00,0.383498,1.217440e+01,3.314700e+00,NaN,0.000485
242904,8,108014750,chr8:108014750:C:T,C,T,0.287835,0.244084,0.537580,0.973981,161,137,24,ADD,-1.333610e+00,0.382785,1.213810e+01,3.306260e+00,NaN,0.000494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259217,5,121514529,chr5:121514529:A:C,A,C,0.322568,0.324321,0.312561,0.943968,161,137,24,ADD,-9.060030e-08,0.437940,4.279860e-14,7.168680e-08,NaN,1.000000
162152,14,92912806,chr14:92912806:A:C,A,C,0.633560,0.621983,0.699645,0.911372,161,137,24,ADD,-8.319820e-08,0.513518,2.624920e-14,5.614130e-08,NaN,1.000000
179356,12,83987692,chr12:83987692:C:T,C,T,0.181869,0.180988,0.186898,1.015630,161,137,24,ADD,-3.698230e-08,0.501406,5.440120e-15,2.555810e-08,NaN,1.000000
106691,12,48061472,chr12:48061472:G:A,G,A,0.513836,0.516479,0.498749,0.993149,161,137,24,ADD,2.573800e-08,0.397146,4.200010e-15,2.245690e-08,NaN,1.000000
291081,11,131255185,chr11:131255185:C:T,C,T,0.577643,0.578661,0.571832,0.910740,161,137,24,ADD,1.442600e-08,0.417528,1.193780e-15,1.197250e-08,NaN,1.000000

Novel hit in CAS? 🤔